steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'poetry', '-f', 'poetry.Dockerfile', '.' ]
  - name: "poetry"
    args: ["export", "--format", "requirements.txt", "--output", "requirements.txt", "--without-hashes"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - functions
    - deploy
    - push-new-reservation-requests
    - --project=trentiemeciel
    - --source=.  
    - --region=europe-west3
    - --entry-point=from_firestore
    - --runtime=python38
    - --memory=128
    - --trigger-event=providers/cloud.firestore/eventTypes/document.create
    - --trigger-resource=projects/trentiemeciel/databases/(default)/documents/pax/{paxId}/requests/{requestId}
    
